name: Manual Tag and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag Name (e.g., v1.0.0)"
        required: true
      release:
        description: "Trigger Release? (yes/no)"
        required: true
        default: "no"

permissions:
  contents: write
  actions: write

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    environment: Tags
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Create Tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ inputs.tag_name }}',
              sha: context.sha
            })

  trigger_release:
    name: Trigger Release
    runs-on: ubuntu-latest
    needs: create_tag
    if: inputs.release == 'yes'
    steps:
      - name: Trigger Release Workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/${{ github.repository }}/dispatches \
               -d '{"event_type": "image_build_and_draft_release", "client_payload": {"tag_name": "${{ inputs.tag_name }}"}}'
